db:
  image: mariadb:10.0
  ports :
   - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=sample
    - MYSQL_USER=user
    - MYSQL_PASSWORD=user

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  ports :
    - "8081:80"
  environment:
    - MYSQL_USERNAME=user
    - MYSQL_PASSWORD=user
  links:
    - db:mysql
